services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatMiniProgramOrderBundle\Controller\:
    resource: '../../Controller/'
  WechatMiniProgramOrderBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramOrderBundle\Service\:
    resource: '../../Service/'
    public: true
  WechatMiniProgramOrderBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true

